// Copyright The Gang Sweden, Inc. All Rights Reserved.
// Curveball / BladeBallArena - online abstraction layer
// Shared types. Deliberately free of any platform SDK include, so this header
// compiles the same whether the active provider is Steam, EOS or a console OSS.

#pragma once

#include "CoreMinimal.h"

#include "MLCOnlineTypes.generated.h"

/** Outcome of any asynchronous online operation. */
UENUM()
enum class EMLCOnlineResult : uint8
{
	Success,
	/** The operation ran and the platform said no (lobby full, session gone, permission denied). */
	Failed,
	/** The caller cancelled, or a newer request superseded this one. */
	Cancelled,
	Timeout,
	/** The active provider does not implement this. Callers must degrade, not assert. */
	NotSupported,
	/** Called before the provider finished starting up. */
	NotReady,
};

/**
 * A player, identified on both axes at once.
 *
 * This type exists because the two identity systems in this game do not agree.
 * The backend keys everything on a LootLocker ULID (party membership, loadouts,
 * presence, grants). Steam lobbies key everything on SteamID64. Every provider
 * API below takes this handle rather than a bare string, so the mapping cannot
 * be forgotten at a call site: if you can name the player, you have both halves.
 *
 * PlatformId is a string, not a uint64, so EOS ProductUserIds and console
 * account IDs fit the same field without a second type.
 */
USTRUCT()
struct FMLCPlayerHandle
{
	GENERATED_BODY()

	/** SteamID64 / EOS ProductUserId / console account id, as text. */
	UPROPERTY()
	FString PlatformId;

	/** LootLocker ULID. The game's identity of record for anything persistent. */
	UPROPERTY()
	FString AccountUlid;

	/** Display name as the platform reports it. Never used as a key. */
	UPROPERTY()
	FString DisplayName;

	bool IsValid() const { return !PlatformId.IsEmpty(); }

	/** True once both halves are known. Party features need this; a bare connect does not. */
	bool IsFullyResolved() const { return !PlatformId.IsEmpty() && !AccountUlid.IsEmpty(); }

	bool operator==(const FMLCPlayerHandle& Other) const { return PlatformId == Other.PlatformId; }
};

FORCEINLINE uint32 GetTypeHash(const FMLCPlayerHandle& Handle)
{
	return GetTypeHash(Handle.PlatformId);
}

/** Lifecycle of the local player's relationship to a match session. */
UENUM()
enum class EMLCSessionState : uint8
{
	None,
	Searching,
	/** No session found, this client is creating one and will host. */
	Creating,
	Joining,
	/** In a session, as host or as a client. Check bIsHost on FMLCSessionInfo. */
	InSession,
	Leaving,
	Failed,
};

/**
 * Everything the game needs to know about the session it is in or has just found.
 *
 * ConnectString is opaque on purpose. Under SteamSockets it is "steam.<SteamID64>";
 * under EOS it is an EOS connect URL. Callers pass it to travel and never parse it.
 */
USTRUCT()
struct FMLCSessionInfo
{
	GENERATED_BODY()

	UPROPERTY()
	FString ConnectString;

	/**
	 * Provider-native session identity (Steam lobby id today).
	 *
	 * Surfaced to Blueprint as FPartyResponse::ticket_id, which used to hold a
	 * GameLift matchmaking ticket. Blueprint may branch on it being non-empty,
	 * so it must always carry something real rather than being left blank.
	 */
	UPROPERTY()
	FString SessionId;

	/**
	 * The matchmaking configuration key, in the same string form the old backend used.
	 *
	 * UMatchmakingData::GetMatchmakingConfigurationFromMatchmakingData reverse-maps
	 * the mode by substring-matching "duel" / "practice" in this string and defaults
	 * to FFA. Keeping the original key format means that code stays correct untouched.
	 */
	UPROPERTY()
	FString ModeKey;

	UPROPERTY()
	int32 CurrentPlayers = 0;

	UPROPERTY()
	int32 MaxPlayers = 0;

	UPROPERTY()
	bool bIsHost = false;
};

/** One player's outcome for a round or a match, as reported to the grant service. */
USTRUCT()
struct FMLCPlayerOutcome
{
	GENERATED_BODY()

	UPROPERTY()
	FMLCPlayerHandle Player;

	UPROPERTY()
	int32 Placement = 0;

	UPROPERTY()
	int32 Kills = 0;

	UPROPERTY()
	int32 Deflections = 0;

	UPROPERTY()
	int32 ScoreEarned = 0;

	/** True if the player was present at the end. Leavers are reported, not omitted. */
	UPROPERTY()
	bool bCompleted = false;
};

/**
 * A round or match result, submitted by both the host and every client.
 *
 * The grant service compares independent reports for the same MatchId + RoundIndex
 * and withholds on divergence, which is what stops a cheating host inflating its
 * own outcome. That only works if clients report too, so this is not host-only.
 */
USTRUCT()
struct FMLCMatchReport
{
	GENERATED_BODY()

	/** Stable for the whole match, generated by the host at match start. */
	UPROPERTY()
	FString MatchId;

	/** -1 for a whole-match report, 0-based otherwise. */
	UPROPERTY()
	int32 RoundIndex = -1;

	UPROPERTY()
	FString ModeKey;

	UPROPERTY()
	FMLCPlayerHandle Reporter;

	UPROPERTY()
	bool bReporterIsHost = false;

	UPROPERTY()
	TArray<FMLCPlayerOutcome> Outcomes;

	/** Client-side clock is untrusted; the service stamps its own. Kept for diagnostics. */
	UPROPERTY()
	FDateTime ReportedAt = FDateTime::MinValue();
};
